apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: paytm
  name: nandhan-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nandhan-deploy
  template:
    metadata:
      labels:
        app: nandhan-deploy
    spec:
      containers:
      - name: cont1
        image: phani2612/nandhan:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: abc
spec:
  type: LoadBalancer
  selector:
    app: nandhan-deploy
  ports:
    - port: 80
      targetPort: 80
